### ISSUE TITLE
Add support for FLUX_LED

### ISSUE THREAD

**Issue by user2684** [myhouse-project/myHouse#235]
please add plugin for [flux_led](https://github.com/beville/flux_led/blob/master/README.md)

Reported by: mojso

**Comment by mojso** [comment]
[2019-01-20 21:20:50] [webserver.py:124 - error()] WARNING: /Indoor/command/desklighton/run: 404: Not Found
where do I make a mistake?

{
  "module_id": "Indoor",
  "section_id": "Sensors",
  "display_name": {
    "en": "Indoor"
  },
  "icon": "fa-home",
  "enabled": true,
  "daily_digest": false,
  "auto_refresh_min": 0,
  "widgets": [
    [
      {
        "widget_id": "desklight",
        "display_name": {
          "en": "Bedroom: Desk Light"
        },
        "keywords": {},
        "enabled": true,
        "size": 2,
        "offset": 0,
        "layout": [
          {
            "type": "button",
            "display_name": {
              "en": "On"
            },
            "actions": [
              "send,Indoor/command/desklighton/run"
            ]
          },
          {
            "type": "button",
            "display_name": {
              "en": "Off"
            },
            "actions": []
          }
        ]
      }
    ]
  ],
  "rules": [],
  "sensors": [
    {
      "module_id": "Indoor",
      "group_id": "command",
      "sensor_id": "desklighton",
      "enabled": true,
      "display_name": {
        "en": "desklighton"
      },
      "plugin": {
        "plugin_name": "command",
        "command_poll": "python -m flux_led 192.168.1.117 --on"
      },
      "format": "string",
      "retention": {
        "realtime_count": 1,
        "realtime_days": 0,
        "recent_days": 0,
        "history_days": 0
      }
    }
  ]
}

**Comment by user2684** [comment]
Hi, I think you are missing the "action" after "run", something like `send,Indoor/command/desklighton/run/save`.
Btw since you are actively looking into myHouse, you might be interested in the high level roadmap of future versions https://github.com/myhouse-project/myHouse/wiki/myHouse-v3.0-Roadmap

**Comment by mojso** [comment]
send,Indoor/command/desklighton/run/save
with this command I get

[2019-01-20 21:02:59] [sensors.py:195 - store()] INFO: [Indoor][command][desklighton] (2019-01-20 21:02:59) saving desklighton: /usr/bin/python: No module named flux_led

flux_led is is installed and work in  terminal

**Comment by user2684** [comment]
Ok, looks like the command is eventually executed but when running `python -m flux_led 192.168.1.117 --on` you get a `/usr/bin/python: No module named flux_led`. Not sure if it is because of a different version of python is executed or by a different user though. Try running `python -m flux_led 192.168.1.117 --on` as the same user myHouse is running (root?)

**Comment by mojso** [comment]
in the terminal works fine, I only have one user where myHouse is, the files from flux_led are in /home/pi/.local/lib/python2.7/site-packages/flux_led

works with pyton2.7

**Comment by user2684** [comment]
I believe if myHouse is running as root, cannot access /home/pi/.local/lib/python2.7/site-packages/flux_led since this is a path the pi user only can leverage. Try installing the flux_led python package system wide, it should show up in /usr/lib/python2.7/ or similar to be seen by root as well.
Also if you run `sudo python -m flux_led 192.168.1.117 --on` I expect you get the same error

**Comment by mojso** [comment]
I reinstall flux_led with sudo and now it works

sudo easy_install flux_led

**Comment by user2684** [comment]
Cool, glad to hear the workaround is working fine!

**Comment by mojso** [comment]
can i triger from rule ?
what am I doing wrong?


RULE

{
  "rule_id": "rainsnowrule",
  "display_name": {
    "en": "rainsnowrule   %lightrainsnow% > %humlight% "
  },
  "keywords": {},
  "enabled": true,
  "severity": "none",
  "run_every": "5 minutes",
  "conditions": [
    "lightrainsnow > humlight"
  ],
  "definitions": {
    "lightrainsnow": "outdoor:humidity:external:hour:avg,-1,-1",
    "humlight": 80
  },
  "actions": [
    "send,Indoor:command:humraindesklight,run,save"
  ]
}


Sensor

{
  "module_id": "Indoor",
  "group_id": "command",
  "sensor_id": "humraindesklight",
  "enabled": true,
  "display_name": {
    "en": "humraindesklight"
  },
  "plugin": {
    "plugin_name": "command",
    "command_poll": "python -m flux_led 192.168.1.117 -c \"#87CEEB\""
  },
  "format": "string",
  "retention": {
    "realtime_count": 1,
    "realtime_days": 0,
    "recent_days": 0,
    "history_days": 0
  }
}

**Comment by user2684** [comment]
couple of things: set severity to something different, e.g. info, otherwise you will not see it triggering and and no logs will show up. Then actions should look like "send,Indoor/command/humraindesklight/run/save". Not very intuitive, sorry but we a re trying to simplify this dramatically in the next release.

**Comment by mojso** [comment]
I get this error

[2019-02-03 23:05:00] [alerter.py:284 - run()] WARNING: error while running rule Indoor:rainsnowrule: Traceback (most recent call last):|  File "/home/pi/myHouse/alerter.py", line 265, in run|    value = split[2]|IndexError: list index out of range|

**Comment by user2684** [comment]
Sorry my mistake. That syntax with run and save does apply only when invoked through the web interface and it basically ask the sensor to poll a measure which in this case would run the command. 
When invoked from a rule you initial syntax was correct was was missing the "value" to send. 
With the command plugin is the command to run (regardless of what is set in the sensor configuration.
So something like the following (not tested), should do the job:
"send,Indoor:command:humraindesklight,python -m flux_led 192.168.1.117 -c '#87CEEB'"

**Comment by mojso** [comment]
this is set in a sensor

{
  "module_id": "Indoor",
  "group_id": "command",
  "sensor_id": "humraindesklight",
  "enabled": true,
  "display_name": {
    "en": "humraindesklight"
  },
  "plugin": {
    "plugin_name": "command",
    "command_poll": "python -m flux_led 192.168.1.117 -c 38,59,67"
  },
  "format": "string",
  "retention": {
    "realtime_count": 1,
    "realtime_days": 0,
    "recent_days": 0,
    "history_days": 0
  }
}

And this is set in a rule

{
  "rule_id": "rainsnowrule",
  "display_name": {
    "en": "rainsnowrule   %lightrainsnow% > %humlight% "
  },
  "enabled": true,
  "severity": "info",
  "run_every": "5 minutes",
  "conditions": [
    "lightrainsnow > humlight"
  ],
  "definitions": {
    "lightrainsnow": "outdoor:humidity:external:hour:avg,-1,-1",
    "humlight": 70
  },
  "actions": [
    "send,Indoor/command/humraindesklight/run/save"
  ]
}

works through, send a command from a button, but not through a rule, maybe a mistake in the rule

**Comment by mojso** [comment]
send,Indoor:command:humraindesklight,python -m flux_led 192.168.1.117 -c 38,59,67"

[2019-02-04 14:05:00] [alerter.py:279 - run()] INFO: [Indoor][rainsnowrule][info] rainsnowrule   79.0 > 70 

this command appears in the log as disply_name but does not yet activate the sensor

Set command is working but send command not, problem with sensor setup or somethings else
[2019-02-05 13:35:00] [sensors.py:195 - store()] INFO: [Indoor][command][humraindesklight] (2019-02-05 13:35:00) saving humraindesklight: python -m flux_led 192.168.1.117 -c "#263b43"


some suggestion

**Comment by mojso** [comment]
I finally found the solution , to trigger from rule

`send,Indoor:command:humraindesklight,sudo python sensors.py Indoor command humraindesklight save`
[From Here -- How to manually pull data out of a sensor?](https://sourceforge.net/p/my-house/wiki/faq/#how-to-manually-pull-data-out-of-a-sensor)

**Comment by user2684** [comment]
Smart approach and glad you solved this one as well! Again, I hope this will be way easier in the next release

**Comment by mojso** [comment]
how to calculate the 
humidity / 10 
In rule  
to get a value from 1 to 9

**I tried this way**

{
  "rule_id": "rainsnowrule2",
  "display_name": {
    "en": "rainsnowrule2   %lightrainsnow2% < %humlight2%  "
  },
  "enabled": true,
  "severity": "none",
  "run_every": "minute",
  "conditions": [
    "'(lightrainsnow2 / numten)' == humlight2"
  ],
  "definitions": {
    "lightrainsnow2": "Indoor:command:rainsnow:hour:avg,-1,-1",
    "humlight2": 7,
    "numten": "10"
  },
  "actions": [
    "send,Indoor:command:humraindesklight2,sudo python sensors.py Indoor command humraindesklight2 save"
  ]
}

**but I get this error**

[2019-02-08 00:08:30] [alerter.py:284 - run()] WARNING: error while running rule Indoor:rainsnowrule2: Traceback (most recent call last):|  File "/home/pi/myHouse/alerter.py", line 226, in run|    sub_evaluation = is_true(definitions[a],operator,definitions[b])|KeyError: "'%exp_0%"|

**Comment by user2684** [comment]
Hi, only comparisons are allowed right now in rules' conditions. Best approach would be to have a sensor already storing the value you want to use in a rule and referencing it. There you can use "command_transform" to run a custom command to do the division.
