### ISSUE TITLE
every day the rtl_433 script stops working

### ISSUE THREAD

**Issue by user2684** [myhouse-project/myHouse#237]
every day the rtl_433 script stops working. this appears in the log file

2018-12-28 16:26:50] [scheduler.py:60 - scheduler_error()] ERROR: EVENT_JOB_ERROR for scheduled task : Exception   File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job|    retval = job.func(*job.args, **job.kwargs)|  File "/home/pi/myHouse/plugin_rtl_433.py", line 79, in run|    if str(value) != str(json_output[key]): found = False|: u'channel'

Reported by: mojso

**Comment by user2684** [comment]
I was able to reproduce the issue, basically the plugin searches for both "model" and "channel" and if one or the other is missing from the rtl_433 output then dies when it should not. Will be fixed in next release. If you want a quick fix, you can try replacing 

`if str(value) != str(json_output[key]): found = False`

with 

`if key in json_output and str(value) != str(json_output[key]): found = False`

in plugin_rtl_433.py.

Below for my own reference the script used for testing the bug.

```
import json
search_string= "{\"model\": \"Prologue sensor\",\"channel\": 2}"
output='{"time" : "2019-01-02 19:21:27", "model" : "Prologue sensor", "id" : 5, "rid" : 110, "dhannel" : 2, "battery" : "OK", "button" : 0, "temperature_C" : 2.900, "humidity" : 65}'
#output='Tuned to 433750000 Hz.'

search_json = json.loads(search_string)
json_output = json.loads(output)
found = True
for key, value in search_json.iteritems():
	if key not in json_output: found = False
	if str(value) != str(json_output[key]): found = False
	print found

```

**Comment by mojso** [comment]
48 hours running without stopping, for now it works well and with the change of frequency

**Comment by mojso** [comment]
my proposal for rtl_433 plugin. if 2 or more frequencies are used, wait on one frequency until it receives information from the sensor, then proceed to the next preset frequency

**Comment by user2684** [comment]
Thanks first of all for confirming the patch fixed the issue!
As for handling the two frequencies, if I've understood correctly, the issue I see with this approach is that while switching frequency (e.g. stopping and restarting rtl_433), messages in between are going to get lost. The other issue I see is that you would likely not to be able to work on two frequencies in a reliable way (unless they are very close) with the same antenna attached to the USB dongle. To achieve what you are looking for, probably best and easiest would be to have a second dongle attached and myHouse being able to work with both independently (not possible right now but will be in the future). Makes sense?

**Comment by mojso** [comment]
works well with changing frequencies. in this case it does not matter if it loses data. But if a device is controlled by a sensor via rtl_433 then every data is important

https://drive.google.com/file/d/15y9uLx6thRbdZ_Buik4sioe__087b6b-/view?usp=drivesdk


and yes, the bug is fixed by changing this line

if str(value) != str(json_output[key]): found = False

With

if key in json_output and str(value) != str(json_output[key]): found = False

**Comment by user2684** [comment]
Thanks, I'll keep this open to keep track of the bug and I've opened the enhancement request #312 for multiple frequency support (will see how to implement it there). Thanks again

**Comment by user2684** [comment]
Adding to the v3.0 development queue

**Comment by user2684** [comment]
Hi, for your information, I've completely re-designed- re-architect myHouse also giving it a new name (eGeoffrey). The basic principles are the same, the software is still open source but now is supposed to be way simpler to configure, use, customize and extend. If you want to give it a look, check out https://www.egeoffrey.com (it is still under testing). 
I've also put together a migration utility to help along to way in case you want to move into the new platform: https://github.com/myhouse-project/myHouse2eGeoffrey
